public with sharing class TestMain {
    public TestMain() {
        /*TestSuperClass SuperClass = new TestSuperClass();
        SuperClass.calc1(1, 2);

        TestSubClass SubClass = new TestSubClass();
        SubClass.calc1(2, 3);
        SubClass.calc2(3, 4);
        */
        //TestSubClass SubClass = new TestSubClass();
        //subclass.succession2(2);

        TestSubClass2 subclass2 = new TestSubClass2();
        subclass2.succession3(3);
    }
}